In [1]:
a,b,c,d = map(int,input('Enter 4 Int:').split())

Enter 4 Int:1 2 3 4


In [2]:
a,b,c,d

(1, 2, 3, 4)

In [3]:
print(a,b,c,d)

1 2 3 4


In [4]:
x,y,z,p = map(float,input('Enter 4 Floats:').split())

Enter 4 Floats:3.4 4.5 6.7 1.5


In [5]:
x,y,z,p

(3.4, 4.5, 6.7, 1.5)

In [6]:
s1,s2,s3,s4 = map(str,input('Enter 4 Strings:').split())

Enter 4 Strings:Indium Chennai DS DE


In [7]:
print(s1,s2,s3,s4)

Indium Chennai DS DE


In [8]:
# NumPy

In [9]:
N = 100000000

In [17]:
%%time
list1 = list(range(N))
for i in range(N):
    list1[i] = list1[i]*list1[i]

CPU times: total: 27.9 s
Wall time: 28.1 s


In [11]:
%%time
list1 = list(range(N))
list1 = [i*i for i in list1] # List Comprehension

CPU times: total: 13.8 s
Wall time: 14 s


In [12]:
%%time
list1 = list(range(N))
list1 = map(lambda i:i*i,list1) # (lambda var:expression,input_data)

CPU times: total: 2.17 s
Wall time: 2.17 s


In [13]:
%%time
list1 = list(range(N))
list_sum = 0
for item in list1:
    list_sum+=item

CPU times: total: 17.9 s
Wall time: 18 s


In [14]:
%%time
list1 = list(range(N))
list_sum = sum(list1)

CPU times: total: 13.2 s
Wall time: 13.5 s


In [15]:
import numpy as np

In [18]:
%%time
arr = np.arange(N)
arr = arr*arr

CPU times: total: 438 ms
Wall time: 426 ms


In [ ]:
# 1 ms = 0.001 Sec
# 438ms = 0.438 Sec

In [19]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: total: 266 ms
Wall time: 279 ms


In [20]:
%%time
arr = np.arange(N)
arr = arr+arr

CPU times: total: 375 ms
Wall time: 379 ms


In [21]:
# An array is a collection of items
#stored at Contiguous location

In [22]:
# The idea is to store multiple items
# of the same type together

In [23]:
# Create the Array

In [24]:
arr = np.arange(5)

In [25]:
print(arr,type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [26]:
arr1 = np.array([0.0,2,4,6,8])

In [27]:
arr1

array([0., 2., 4., 6., 8.])

In [28]:
list1 = [0.0,2,4,6,8]

In [29]:
list1

[0.0, 2, 4, 6, 8]

In [30]:
type(list1[0])

float

In [31]:
type(list1[1])

int

In [32]:
arr1

array([0., 2., 4., 6., 8.])

In [33]:
print(arr1,type(arr1))

[0. 2. 4. 6. 8.] <class 'numpy.ndarray'>


In [34]:
arr1.dtype

dtype('float64')

In [35]:
arr

array([0, 1, 2, 3, 4])

In [36]:
arr.dtype

dtype('int32')

In [37]:
arr.ndim

1

In [38]:
# linear Algebra

#[ 1  2
 # 3  4]

In [39]:
arr

array([0, 1, 2, 3, 4])

In [40]:
arr.size

5

In [41]:
arr.itemsize

4

In [42]:
arr1

array([0., 2., 4., 6., 8.])

In [43]:
arr1.size

5

In [44]:
arr1.itemsize

8

In [45]:
arr2d = np.array([
                [1,2,3],
                [4,5,6]
])

In [46]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr2d1 = ([[1,2,3],[4,5,6]])

In [48]:
arr2d1

[[1, 2, 3], [4, 5, 6]]

In [49]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr2d.ndim

2

In [51]:
arr1

array([0., 2., 4., 6., 8.])

In [52]:
arr1.ndim

1

In [53]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr2d.shape

(2, 3)

In [55]:
# (2,3)==>(Row , Column)

In [56]:
# (3, 3)

In [63]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
1729* np.ones((2,2))

array([[1729., 1729.],
       [1729., 1729.]])

In [66]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [67]:
np.random.randn(2,3) # n specifies normal distribution

array([[-0.93193821, -0.02324433, -1.04904957],
       [-0.9435952 , -0.48438114,  0.2141938 ]])

In [68]:
np.random.rand(2,3) # random numbers

array([[0.72890632, 0.34133786, 0.60091268],
       [0.05433955, 0.50004168, 0.35344567]])

In [69]:
np.random.rand(3,3)

array([[0.78551087, 0.03136873, 0.5460665 ],
       [0.35378886, 0.11894327, 0.91679805],
       [0.92402774, 0.6834248 , 0.65887911]])

In [70]:
np.random.rand(10,1)

array([[0.38315496],
       [0.95690294],
       [0.25509796],
       [0.47559237],
       [0.75528274],
       [0.34220463],
       [0.90427174],
       [0.60559034],
       [0.95092478],
       [0.98978564]])

In [71]:
np.random.randint(0,100,(2,3))

array([[17, 26, 65],
       [ 8, 13, 68]])

In [72]:
np.arange(7,71,5)

array([ 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67])

In [73]:
# numpy Operations

In [78]:
arr1 = np.random.rand(3,4)

In [79]:
arr1

array([[0.31944605, 0.2438149 , 0.51507962, 0.43587548],
       [0.90522444, 0.76373978, 0.53977021, 0.31266541],
       [0.08125379, 0.30301996, 0.41126303, 0.53395216]])

In [80]:
arr2 = np.random.rand(3,4)

In [81]:
arr2

array([[0.65789676, 0.43424273, 0.89097432, 0.86120427],
       [0.42786188, 0.41643451, 0.09601584, 0.29263503],
       [0.99021785, 0.58570312, 0.5076453 , 0.66991643]])

In [82]:
arr1 + arr2

array([[0.97734281, 0.67805762, 1.40605394, 1.29707974],
       [1.33308632, 1.18017428, 0.63578605, 0.60530044],
       [1.07147164, 0.88872308, 0.91890833, 1.20386859]])

In [83]:
arr1 - arr2

array([[-0.33845071, -0.19042783, -0.3758947 , -0.42532879],
       [ 0.47736257,  0.34730527,  0.44375436,  0.02003038],
       [-0.90896406, -0.28268316, -0.09638228, -0.13596427]])

In [84]:
arr1*arr2

array([[0.21016252, 0.10587485, 0.45892271, 0.37537782],
       [0.38731103, 0.3180476 , 0.05182649, 0.09149685],
       [0.08045895, 0.17747974, 0.20877574, 0.35770332]])

In [85]:
# Matrix Multiplication

In [86]:
arr1 / arr2

array([[0.4855565 , 0.56147146, 0.57810827, 0.50612322],
       [2.11569315, 1.83399734, 5.62167848, 1.06844834],
       [0.08205648, 0.51736102, 0.81013855, 0.79704294]])

In [87]:
np.sin(arr1)

array([[0.31404068, 0.24140644, 0.49260414, 0.42220418],
       [0.78656377, 0.69162735, 0.51393888, 0.30759591],
       [0.08116441, 0.29840393, 0.39976736, 0.50893933]])

In [88]:
np.cos(arr1)

array([[0.94940953, 0.9704241 , 0.8702535 , 0.90650076],
       [0.61750906, 0.72225454, 0.8578268 , 0.95151708],
       [0.99670073, 0.95443967, 0.91661664, 0.86080239]])

In [89]:
np.sqrt(arr1)

array([[0.56519558, 0.49377616, 0.71769048, 0.66020866],
       [0.95143284, 0.87392206, 0.73469055, 0.55916492],
       [0.2850505 , 0.55047249, 0.64129792, 0.7307203 ]])

In [90]:
arr1 = np.arange(6)

In [91]:
arr1

array([0, 1, 2, 3, 4, 5])

In [92]:
arr1.shape

(6,)

In [93]:
arr1 =arr1.reshape((3,2))

In [94]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [95]:
arr2 = np.arange(6)

In [96]:
arr2

array([0, 1, 2, 3, 4, 5])

In [97]:
arr2 = arr2.reshape((2,3))

In [98]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [99]:
arr3 = np.arange(9)

In [100]:
arr3 = arr3.reshape((3,3))

In [101]:
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
arr4 = np.arange(12)

In [103]:
arr4 = arr4.reshape((3,4))

In [104]:
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
arr5 = np.arange(12)

In [106]:
arr5 = arr5.reshape((4,3))

In [107]:
arr5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [108]:
arr6 = np.arange(6).reshape((3,2)) # chaining

In [109]:
arr6

array([[0, 1],
       [2, 3],
       [4, 5]])

In [110]:
arr6+1   # Not goint to update the original Matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [111]:
arr6.T # Transpose

array([[0, 2, 4],
       [1, 3, 5]])

In [112]:
# Stats With NumPy

In [113]:
arr = np.arange(10)

In [114]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.amin(arr)

0

In [116]:
np.amax(arr)

9

In [117]:
np.mean(arr)

4.5

In [118]:
np.var(arr)

8.25

In [119]:
np.std(arr)

2.8722813232690143

In [120]:
np.median(arr)

4.5

In [121]:
# 0,0,1,1,1,2,3,3,3,3,4  Mode -->3 Mode-->1 Mode-->2

In [122]:
# Case Study

In [123]:
# weights

In [124]:
arr1 = np.random.randint(50,80,100)

In [125]:
arr1

array([56, 53, 59, 79, 62, 57, 76, 74, 66, 78, 71, 61, 58, 54, 54, 71, 66,
       70, 68, 79, 72, 79, 74, 69, 53, 60, 77, 73, 75, 71, 63, 58, 63, 53,
       67, 66, 59, 52, 59, 64, 59, 52, 79, 70, 58, 74, 57, 76, 53, 73, 57,
       70, 72, 59, 50, 72, 58, 58, 76, 50, 60, 61, 68, 75, 55, 75, 55, 68,
       60, 58, 55, 78, 56, 59, 55, 79, 74, 66, 51, 53, 58, 76, 60, 75, 69,
       56, 75, 74, 57, 52, 59, 50, 50, 54, 50, 53, 70, 55, 66, 51])

In [126]:
# Height

In [127]:
arr2 = np.random.randint(150,185,100)

In [128]:
arr2

array([165, 170, 168, 160, 158, 179, 177, 159, 161, 165, 153, 150, 180,
       155, 181, 168, 184, 150, 170, 161, 170, 156, 178, 183, 183, 176,
       158, 174, 169, 176, 161, 157, 177, 156, 184, 182, 152, 154, 171,
       163, 159, 183, 172, 154, 156, 181, 182, 155, 151, 180, 177, 171,
       161, 151, 179, 152, 174, 168, 175, 181, 176, 177, 154, 165, 159,
       161, 171, 161, 163, 183, 160, 156, 179, 155, 164, 165, 156, 155,
       160, 151, 177, 156, 156, 165, 179, 161, 171, 183, 172, 157, 154,
       170, 165, 172, 175, 161, 161, 169, 167, 154])

In [129]:
# Age

In [130]:
arr3 = np.random.randint(17,22,100)

In [131]:
arr3

array([21, 18, 20, 18, 17, 17, 21, 21, 21, 18, 20, 19, 19, 21, 20, 20, 20,
       18, 21, 21, 19, 17, 20, 18, 20, 21, 17, 18, 18, 20, 20, 18, 19, 18,
       18, 18, 18, 19, 18, 18, 18, 21, 17, 21, 18, 20, 19, 17, 18, 21, 19,
       20, 21, 21, 17, 17, 17, 21, 19, 20, 18, 21, 21, 18, 17, 17, 18, 20,
       20, 21, 17, 17, 17, 21, 17, 21, 20, 20, 19, 17, 20, 19, 19, 17, 21,
       21, 17, 17, 17, 18, 18, 21, 18, 18, 18, 18, 18, 20, 19, 19])

In [132]:
arr1

array([56, 53, 59, 79, 62, 57, 76, 74, 66, 78, 71, 61, 58, 54, 54, 71, 66,
       70, 68, 79, 72, 79, 74, 69, 53, 60, 77, 73, 75, 71, 63, 58, 63, 53,
       67, 66, 59, 52, 59, 64, 59, 52, 79, 70, 58, 74, 57, 76, 53, 73, 57,
       70, 72, 59, 50, 72, 58, 58, 76, 50, 60, 61, 68, 75, 55, 75, 55, 68,
       60, 58, 55, 78, 56, 59, 55, 79, 74, 66, 51, 53, 58, 76, 60, 75, 69,
       56, 75, 74, 57, 52, 59, 50, 50, 54, 50, 53, 70, 55, 66, 51])

In [133]:
arr2

array([165, 170, 168, 160, 158, 179, 177, 159, 161, 165, 153, 150, 180,
       155, 181, 168, 184, 150, 170, 161, 170, 156, 178, 183, 183, 176,
       158, 174, 169, 176, 161, 157, 177, 156, 184, 182, 152, 154, 171,
       163, 159, 183, 172, 154, 156, 181, 182, 155, 151, 180, 177, 171,
       161, 151, 179, 152, 174, 168, 175, 181, 176, 177, 154, 165, 159,
       161, 171, 161, 163, 183, 160, 156, 179, 155, 164, 165, 156, 155,
       160, 151, 177, 156, 156, 165, 179, 161, 171, 183, 172, 157, 154,
       170, 165, 172, 175, 161, 161, 169, 167, 154])

In [134]:
arr3

array([21, 18, 20, 18, 17, 17, 21, 21, 21, 18, 20, 19, 19, 21, 20, 20, 20,
       18, 21, 21, 19, 17, 20, 18, 20, 21, 17, 18, 18, 20, 20, 18, 19, 18,
       18, 18, 18, 19, 18, 18, 18, 21, 17, 21, 18, 20, 19, 17, 18, 21, 19,
       20, 21, 21, 17, 17, 17, 21, 19, 20, 18, 21, 21, 18, 17, 17, 18, 20,
       20, 21, 17, 17, 17, 21, 17, 21, 20, 20, 19, 17, 20, 19, 19, 17, 21,
       21, 17, 17, 17, 18, 18, 21, 18, 18, 18, 18, 18, 20, 19, 19])

In [135]:
# arr1,arr2,arr3---> min-->weight Height Age

In [136]:
np.concatenate((arr1,arr2,arr3)).shape

(300,)

In [137]:
arr4 = np.concatenate((arr1,arr2,arr3))

In [138]:
arr4

array([ 56,  53,  59,  79,  62,  57,  76,  74,  66,  78,  71,  61,  58,
        54,  54,  71,  66,  70,  68,  79,  72,  79,  74,  69,  53,  60,
        77,  73,  75,  71,  63,  58,  63,  53,  67,  66,  59,  52,  59,
        64,  59,  52,  79,  70,  58,  74,  57,  76,  53,  73,  57,  70,
        72,  59,  50,  72,  58,  58,  76,  50,  60,  61,  68,  75,  55,
        75,  55,  68,  60,  58,  55,  78,  56,  59,  55,  79,  74,  66,
        51,  53,  58,  76,  60,  75,  69,  56,  75,  74,  57,  52,  59,
        50,  50,  54,  50,  53,  70,  55,  66,  51, 165, 170, 168, 160,
       158, 179, 177, 159, 161, 165, 153, 150, 180, 155, 181, 168, 184,
       150, 170, 161, 170, 156, 178, 183, 183, 176, 158, 174, 169, 176,
       161, 157, 177, 156, 184, 182, 152, 154, 171, 163, 159, 183, 172,
       154, 156, 181, 182, 155, 151, 180, 177, 171, 161, 151, 179, 152,
       174, 168, 175, 181, 176, 177, 154, 165, 159, 161, 171, 161, 163,
       183, 160, 156, 179, 155, 164, 165, 156, 155, 160, 151, 17

In [139]:
#(3,100)   Weight--->100
       #   Height-->100
        #  Age----->100   (w(max),h(max),a(max))
            #             (w(min),h(min),a(min))

In [140]:
np.amin(arr4)

17

In [141]:
np.amax(arr4)

184

In [142]:
np.vstack((arr1,arr2,arr3)).shape

(3, 100)

In [143]:
# Weight-->100
# Height-->100
# Age----->100

In [144]:
arr2d = np.vstack((arr1,arr2,arr3))

In [145]:
arr2d

array([[ 56,  53,  59,  79,  62,  57,  76,  74,  66,  78,  71,  61,  58,
         54,  54,  71,  66,  70,  68,  79,  72,  79,  74,  69,  53,  60,
         77,  73,  75,  71,  63,  58,  63,  53,  67,  66,  59,  52,  59,
         64,  59,  52,  79,  70,  58,  74,  57,  76,  53,  73,  57,  70,
         72,  59,  50,  72,  58,  58,  76,  50,  60,  61,  68,  75,  55,
         75,  55,  68,  60,  58,  55,  78,  56,  59,  55,  79,  74,  66,
         51,  53,  58,  76,  60,  75,  69,  56,  75,  74,  57,  52,  59,
         50,  50,  54,  50,  53,  70,  55,  66,  51],
       [165, 170, 168, 160, 158, 179, 177, 159, 161, 165, 153, 150, 180,
        155, 181, 168, 184, 150, 170, 161, 170, 156, 178, 183, 183, 176,
        158, 174, 169, 176, 161, 157, 177, 156, 184, 182, 152, 154, 171,
        163, 159, 183, 172, 154, 156, 181, 182, 155, 151, 180, 177, 171,
        161, 151, 179, 152, 174, 168, 175, 181, 176, 177, 154, 165, 159,
        161, 171, 161, 163, 183, 160, 156, 179, 155, 164, 165, 156, 15

In [146]:
np.amin(arr2d)

17

In [147]:
# min( Weight, Height, Age)

In [148]:
np.amin(arr2d,axis=1)

array([ 50, 150,  17])

In [149]:
np.amax(arr2d,axis=1)

array([ 79, 184,  21])

In [150]:
np.mean(arr2d,axis=1)

array([ 63.63, 166.52,  18.95])

In [151]:
np.median(arr2d,axis=1)

array([ 61., 165.,  19.])

In [152]:
# concatenate vs vstack 

In [153]:
arrv = np.array([10,'Indium',30])

In [154]:
arrv

array(['10', 'Indium', '30'], dtype='<U11')

In [155]:
arrv.dtype

dtype('<U11')

In [156]:
arrv.itemsize

44

In [157]:
arrn = np.array([10,-1,3,56,89,-2])

In [158]:
arrn

array([10, -1,  3, 56, 89, -2])

In [159]:
arrn.dtype

dtype('int32')

In [160]:
arrn.max()

89

In [161]:
arrn.argmax()

4

In [162]:
arrn.min()

-2

In [163]:
arrn.argmin()

5

In [164]:
arrn

array([10, -1,  3, 56, 89, -2])

In [165]:
arrn.sort()

In [166]:
arrn

array([-2, -1,  3, 10, 56, 89])

In [167]:
arrn.sum()

155

In [168]:
# enumerate

In [169]:
arre = np.array([10,10,20,20,10,10])

In [170]:
arre

array([10, 10, 20, 20, 10, 10])

In [172]:
for item in arre:
    print(item)

10
10
20
20
10
10


In [174]:
for index,number in enumerate(arre):
    print(index,number)

0 10
1 10
2 20
3 20
4 10
5 10


In [175]:
for i,n in enumerate(arre):
    if n==10:
        print(n)
        print(i)

10
0
10
1
10
4
10
5


In [177]:
arre

array([10, 10, 20, 20, 10, 10])

In [178]:
arre[0]

10

In [179]:
arre[1:3]

array([10, 20])

In [180]:
arre[1:6]

array([10, 20, 20, 10, 10])

In [181]:
arre[2:5]

array([20, 20, 10])

In [182]:
arrn

array([-2, -1,  3, 10, 56, 89])

In [184]:
arrn.sum()

155

In [185]:
arrn.cumsum()

array([ -2,  -3,   0,  10,  66, 155], dtype=int32)

In [186]:
arrn.cumprod()

array([    -2,      2,      6,     60,   3360, 299040], dtype=int32)

In [187]:
# go to the documentation and accordingly you can apply various functions

In [189]:
#arrn.argpartition()